# General Exit codes
EXIT_CODE_INVALID_CREDENTIALS = 200
EXIT_CODE_BAD_REQUEST = 201
EXIT_CODE_UNKNOWN_ERROR = 3

# Trigger Refresh error codes
EXIT_CODE_REFRESH_ERROR = 205
EXIT_CODE_INVALID_DATASET_ID = 206
EXIT_CODE_REFRESH_ALREADY_RUNNING = 207

# Verify status exit codes
EXIT_CODE_FINAL_STATUS_SUCCESS = 0
EXIT_CODE_FINAL_STATUS_INCOMPLETE = 210
EXIT_CODE_FINAL_STATUS_FAILED = 211
EXIT_CODE_FINAL_STATUS_INVALID = 212
EXIT_CODE_UNKNOWN_STATUS = 213